<?php

/*
 * ByteHoard 2.1
 * Copyright (c) Andrew Godwin & contributors 2004
 *
 *   Installer2 Files Functions
 *   $Id$
 *
 */
 
function bhi_write_config_file($install) {
	global $bhconfig;

	$install['type'] = str_replace(".inc.php", "", $install['dbmod']);
	
	$contents = "<"."?php\n\n".
	"# ByteHoard2 Configuration file\n".
	"# Generated at ".date("l dS of F Y h:i:s A")." [".time()."]\n".
	"# Generated by ByteHoard ".$bhconfig['version']."\n".
	"# ByteHoard2 is released under the GPL.\n".
	"# http://www.bytehoard.org\n\n".
	"";
	
	foreach ($install as $variable=>$value) {
		$contents .= "$"."dbconfig['".$variable."'] = \"".$value."\";\n";
	}
	
	$contents .= "\n\n?".">";
	
	$fn = fopen("../config.inc.php", "w");
	if ($fn === FALSE) {
		return false;
	}
	fputs($fn, $contents);
	fclose($fn);
	
	return true;
}